### ISSUE TITLE
Enable omitted in generated HDL

### ISSUE THREAD

**Issue by christiaanb** [clash-lang/clash-compiler#1556]

**Comment by DigitalBrains1** [comment]
Circuit enable lines can under certain circumstances get disconnected, permanently disabling the circuit without warning.

The following code compiles without warnings and errors, but running the testsuite in the generated HDL reveals that the output is stuck at the value 0 instead of incrementing. This happens because the signal `enMerged` is duplicated as `enMerged1`. The former is assigned the correct value, but the latter is used as the circuit enable without ever being assigned a value. Its default of `False` means that the circuit is never enabled.

The issue was introduced with commit d547dee8a33e2a3cddd7772bbf0df8e587f45d27.

```Haskell
module T1556 where

import Clash.Prelude
import qualified Clash.Explicit.Prelude as CEP
import Clash.Explicit.Testbench

topEntity
    :: Clock System
    -> Reset System
    -> Enable System
    -> Signal System (Unsigned 8)
topEntity clk rst en = o2
    where
        o1 = withClockResetEnable clk rst enMerged $ register 1 $ succ <$> o1
        o2 = CEP.register clk rst enMerged 0 o1
        enMerged = CEP.enable en (pure True)
{-# NOINLINE topEntity #-}

testBench :: Signal System Bool
testBench = done
    where
        o = topEntity clk rst en
        expectedOutput
            = outputVerifier' clk rst (0 :> 1 :> 2 :> Nil)
        done = expectedOutput o
        clk = tbSystemClockGen (not <$> done)
        rst = systemResetGen
        en = tbEnableGen
```
