### ISSUE TITLE
De-"internalize" Clash.Sized.Internal.Index.fromSNat 

### ISSUE THREAD

**Issue by blaxill** [clash-lang/clash-compiler#797]
`Clash.Sized.Internal.Index.fromSNat` is a type safe `snatToNum`, it's currently not exported from `Clash.Prelude` or `Clash.Sized.Index`, but I've been using it increasingly and think it should be exported at a more discoverable level. Is there any disagreement to this?

Side note, currently the type signature is
`fromSNat :: (KnownNat m, CmpNat n m ~ 'LT) => SNat n -> Index m`, convention in the rest of Clash seems to be to use inequality operators e.g. `fromSNat :: (KnownNat m, n <= m + 1) => SNat n -> Index m`, is there a reason for this difference? When the constraint styles are mixed, it seems to require carrying around both styles in calling code.

**Comment by christiaanb** [comment]
I'm in agreement with the export, I think it's an oversight that it wasn't exported form `Clash.Sized.Index` looking at the commit that introduced it.

W.r.t the constraint, `CmpNat n m ~ 'LT` describes it in a less round-about way than `n <= m + 1`, however, the solver in the natnormalise plugin is much more helpful with `n <= m + 1` constraint. So from a practical/usability point of view I agree that we update the constraint as well. It's good that `fromSNat` wasn't exported from Prelude, otherwise we would've violated our intention to keep the API stable from 1.0 forward.
